# Generated by Django 4.0.5 on 2022-08-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_advancement_used_language_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advancement',
        ),
    ]
