# Generated by Django 4.0.5 on 2022-08-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_advancement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_Id', models.IntegerField()),
                ('Participant_Id', models.IntegerField()),
                ('Wrote_Code', models.TextField(default='')),
                ('Used_Language', models.CharField(default='c', max_length=30)),
                ('Score', models.IntegerField(default=0)),
                ('Percentage', models.IntegerField(default=0)),
                ('Color', models.CharField(default='black', max_length=30)),
                ('Results', models.CharField(default='', max_length=500)),
                ('Number_Of_Tests', models.IntegerField(default=0)),
            ],
        ),
    ]
