# Generated by Django 4.0.5 on 2022-08-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_test_expected_output_alter_test_input'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
