# Generated by Django 4.0.5 on 2022-08-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_Id', models.IntegerField()),
                ('Python_User_Code', models.TextField(default='#write your code here')),
                ('Python_Server_code', models.TextField(default='#write your code here')),
                ('Java_User_Code', models.TextField(default='//write your code here')),
                ('Java_Server_code', models.TextField(default='//write your code here')),
                ('NodeJs_User_Code', models.TextField(default='//write your code here')),
                ('NodeJS_Server_code', models.TextField(default='//write your code here')),
                ('C_User_Code', models.TextField(default='//write your code here')),
                ('C_Server_code', models.TextField(default='//write your code here')),
                ('Cpp_User_Code', models.TextField(default='//write your code here')),
                ('Cpp_Server_code', models.TextField(default='//write your code here')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='Memory_Limit',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Time_Limit',
        ),
        migrations.AddField(
            model_name='problem',
            name='Time_Limit_Per_Test',
            field=models.FloatField(default=1),
        ),
    ]
