# Generated by Django 4.0.5 on 2022-08-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_code_remove_test_memory_limit_remove_test_time_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='Statement',
        ),
        migrations.AddField(
            model_name='problem',
            name='Image_Url',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='Statement_Url',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
