# Generated by Django 4.0.5 on 2022-08-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_Id', models.IntegerField()),
                ('Participant_Id', models.IntegerField()),
                ('Wrote_Code', models.TextField()),
                ('Used_Language', models.CharField(max_length=30)),
                ('Score', models.IntegerField(default=0)),
                ('Percentage', models.IntegerField(default=0)),
                ('Color', models.CharField(default='black', max_length=30)),
                ('Results', models.CharField(default='', max_length=500)),
                ('Number_Of_Tests', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Score', models.IntegerField(default=0)),
                ('Solved_Problems', models.IntegerField(default=0)),
                ('Number_Of_Tests', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, upload_to='Problem_image')),
                ('Statement', models.ImageField(blank=True, upload_to='Problem_statement')),
                ('Score', models.IntegerField()),
                ('Default_Python_Code', models.TextField()),
                ('Number_Of_Tests', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_Id', models.IntegerField()),
                ('Test_Id', models.IntegerField()),
                ('Input', models.CharField(max_length=1000)),
                ('Expected_Output', models.CharField(max_length=1000)),
                ('Score', models.IntegerField()),
            ],
        ),
    ]
