# Generated by Django 4.0.5 on 2022-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_problem_default_python_code_test_memory_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancement',
            name='Used_Language',
            field=models.CharField(default='c', max_length=30),
        ),
        migrations.AlterField(
            model_name='advancement',
            name='Wrote_Code',
            field=models.TextField(default=''),
        ),
    ]
