# Generated by Django 4.0.5 on 2022-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_advancement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Expected_Output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='Input',
            field=models.TextField(),
        ),
    ]
