# Generated by Django 4.0.5 on 2022-08-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_Id', models.IntegerField()),
                ('Test_Id', models.IntegerField()),
                ('Input', models.TextField()),
                ('Expected_Output', models.TextField()),
                ('Time_Limit', models.FloatField()),
                ('Memory_Limit', models.FloatField()),
                ('Score', models.IntegerField()),
            ],
        ),
    ]
