# Generated by Django 4.0.5 on 2022-08-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_problem_image_remove_problem_statement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.RemoveField(
            model_name='advancement',
            name='Used_Language',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='Solved_Problems',
        ),
        migrations.AddField(
            model_name='participant',
            name='First_Student_Name',
            field=models.CharField(default='BOUTASKNITE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='Second_Student_Name',
            field=models.CharField(default='DAHIMI', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='Python_Server_Code',
            field=models.TextField(default='#write your code here'),
        ),
        migrations.AddField(
            model_name='problem',
            name='Python_User_Code',
            field=models.TextField(default='#write your code here'),
        ),
        migrations.AddField(
            model_name='test',
            name='Type',
            field=models.CharField(default='submit', max_length=10),
            preserve_default=False,
        ),
    ]
